lib/util/util.c

program_is_loaded() would close file descriptor 0, this patch avoids
it. Closing FD 0 in my scenario was causing a "No such file or
directory" error when trying to bpf_object__load() an object
which has the .attach_prog_fd attribute set.

fix program_is_loaded() so it will not close fd 0

---

headers/bpf/bpf_trace_helpers.h
headers/linux/bpf.h

Update bpf.h to the v5.6-rc2 revision. Also added the
bpf_trace_helpers.h include file as it helps defining trace BPF
functions.

headers/linux: update bpf.h and add bpf_trace_helpers.h

---

headers/linux/bpf.h

This change also required the linux bpf.h file to be updated.

libbpf: Update libbpf to the latest version

---

configure

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

configure: Add check for libpcap

---

lib/testing/test_runner.sh
xdp-dump/Makefile
xdp-dump/test-xdpdump.sh
xdp-dump/xdpdump.c

xdp-dump: add first set of selftests

---

lib/common.mk
lib/testing/test_runner.sh
lib/util/Makefile
lib/util/params.c
lib/util/util.mk
lib/util/xpcapng.c
lib/util/xpcapng.h
packaging/rpm/xdp-tools.spec
xdp-dump/README.org
xdp-dump/test-xdpdump.sh
xdp-dump/xdpdump.c

Adding support for PcapNG, this fixes issue #12

xdp-dump: add PcapNG support

---

xdp-dump/test-xdpdump.sh

xdp-dump: fix selftest with older version of capinfos

---

packaging/rpm/README.org

packaging/rpm: update release document

---

headers/xdp/parsing_helpers.h

Signed-off-by: Štěpán Horáček <shoracek@redhat.com>

xdp-filter: Add basic IPv6 extension header support

---

xdp-filter/tests/test-xdp-filter.sh
xdp-filter/xdp-filter.c

This change makes makes port removal behave as expected: if `port --remove` specifies some mode/protocol, it removes only what is specified (compared to the current state, where it removes also the default values of unspecified mode/protocol).
Fixes #52.

Consistent port removal

---

lib/testing/test_runner.sh

While trying to fix the problem with leftover processes due to stop_background not being called, I found that some sometimes stop_background did not stop the command completely, so I fixed that also.

Clean processes

---

configure
lib/defines.mk
lib/libxdp/libxdp.c
lib/util/compat.h
lib/util/params.c
lib/util/util.c

Just a draft to track progress.
Comments are welcome. No idea if this is a good way of doing such stuff...
I still have the error:
```
xdp-dispatcher.c:5:10: fatal error: 'bpf/bpf_helpers.h' file not found
#include <bpf/bpf_helpers.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
```

Fix compiling on OpenWrt

---

xdp-dump/tests/test-xdpdump.sh

xdpdump: fix selftest to work with latest tcpdump

---

xdp-dump/tests/test-xdpdump.sh
xdp-dump/xdpdump.c

xdpdump: make xdpdump aware of XDP_MODE_HW

---

lib/libxdp/libxdp.c

The dispatcher prog is opened using the open_file path, then loaded onto
the interface, where down the call chain xdp_program__load is called.
This function directly invokes the xdp_program__fill_from_fd helper, but
fails to take into account that it consumes the fd that is passed in (as
it is stashed in the xdp_prog structure).
In all other call sites (wrapped using xdp_program__from_fd), the fd
being consumed is acquired right before it is passed in, so the
ownership transfer works as expected.
All in all, this leads to release paths of the xdp_prog and the bpf_prog
both trying to call close on the same fd, where the xdp_program__close
wins due to it being early in the call chain, and the
bpf_object__unload -> bpf_program__unload's close call gets -EBADF.
Fix this by duplicating the …

xdp: Prevent double close of dispatcher prog fd

---

lib/libxdp/libxdp.c

Fix a couple of places where we don't handle errno correctly.

Fix errno handling in libxdp

---

lib/libxdp/xsk.c

Fixes: #123
Signed-off-by: arikachen <chenqijun@corp.netease.com>

libxdp: get queue num from sysfs in xsk

---

lib/libxdp/libxdp.c

It seems[0] that there are some systems that will force-close fds 0, 1 and
2 if they don't refer to the regular std{in,out,err} streams. To make sure
we don't run afoul of this, let's use 3 as the minimum fd when cloning file
descriptors.
[0] https://lore.kernel.org/r/CAADnVQKVKY8o_3aU8Gzke443+uHa-eGoM0h7W4srChMXU1S4Bg@mail.gmail.com

libxdp: use 3 as the minimum fd number when cloning fds

---

Makefile
headers/xdp/libxdp.h
lib/libxdp/Makefile
lib/libxdp/libxdp.c
lib/libxdp/libxdp_internal.h
lib/libxdp/tests/test-libxdp.sh
lib/libxdp/tests/test_runner.sh
lib/libxdp/xsk.c

Fix a couple of build and link errors for libxdp, and add a selftest to make
sure they don't resurface.
Fixes #135.

Fix libxdp build and linking errors

---

.gitignore
lib/common.mk
lib/libxdp/.gitignore
lib/libxdp/Makefile
lib/libxdp/libxdp.3
xdp-dump/xdpdump.8
xdp-filter/xdp-filter.8
xdp-loader/xdp-loader.8

Include man pages in source code repository

---

lib/libxdp/README.org

Fixes #145.
Cc @magnus-karlsson @cloftus

libxdp: Update version requirement documentation for AF_XDP

---

configure
lib/Makefile
lib/export-man.el
lib/libxdp/libxdp.3
packaging/rpm/xdp-tools.spec
version.mk
xdp-dump/xdpdump.8
xdp-filter/xdp-filter.8
xdp-loader/xdp-loader.8

Fixes and version bump for release 1.2.1
Cc @cloftus

Release 1.2.1

---

lib/libxdp/libxdp.c

Coverity discovered a new issue created by one of the earlier refactorings. This PR fixes that...

Fix for coverity-discovered issue

---

configure
lib/libxdp/Makefile
lib/libxdp/libxdp.3
version.mk
xdp-dump/xdpdump.8
xdp-filter/xdp-filter.8
xdp-loader/xdp-loader.8

Another bugfix release to get the right version in the libxdp .pc file
Cc @cloftus

Release v1.2.2

---

lib/libxdp/xsk.c

The xsk_lookup_program() function uses xdp_multiprog__get_from_ifindex()
without closing the resulting multiprog. Fix this by moving the call to
xdp_program__clone() inside xsk_lookup_program() so we can close the
multiprog instance before returning.

xsk: Don't leak xdp_multiprog reference

---

configure
lib/libxdp/libxdp.c
lib/libxdp/xsk.c
lib/testing/test-tool.c
xdp-dump/xdpdump.c
xdp-loader/xdp-loader.8

Another bunch of deprecations...

Update libbpf version

---

lib/libxdp/xsk.c

Creating AF_XDP sockets with the XDP_SHARED_UMEM flag set fails when two devices
ifindex (and the queue_id) are the same. This can happen with devices in
different network namespaces.
In the shared UMEM mode, each Xsk is expected to have a dedicated fill and
completion queue. Context data about those queues is stored in a linked-list
within the UMEM object.
The comparison performed to pick the right context for an Xsk prior to calling
bind() only takes into account the ifindex and queue_id of the network device.
However, the ifindex is not a "system-wide" unique identifier, it is unique only
within a network namespace. This results in attributing the same xsk_ctx to
different Xsks.
To fix this, we retrieve the netns_cookie associated with the socket at its
creation and add it in the …

libxdp: make shared xsk creation network namespace aware

---

lib/util/stats.c
lib/util/util.c
xdp-dump/xdpdump.c

openwrt: fix cross platform compiling.

---

lib/libxdp/libxdp.c

Coverity pointed out that we introduced use after free errors when
converting xdp_program__from_fd() to call xdp_program__close() instead of
just freeing the xdp_program object. However, we do need to call the
destructor or we won't free up all resources. At the same time, we don't
want xdp_program__from_fd() to take ownership of the fd, since that
function is also public API.
To fix this, change xdp_program__fill_from_fd() so it always duplicates the
fd before filling in the object, taking ownership of the duplicate instead
of the original fd. We already did this in a couple of call sites, which we
can then get rid of, leading to an overall simplification.

libxdp: always clone program fd before taking ownership of it

---

.gitmodules
lib/libxdp/xsk_def_xdp_prog.c
lib/libxdp/xsk_def_xdp_prog_5.3.c

Also fix section names in xsk programs.

Update to use libbpf v1.0.0 from upstream

---

lib/libxdp/libxdp.c

While the libxdp locking protects against concurrent updates of the same
multiprog, there's still a race window where the old multiprog can get
detached by another application while we build its replacement. To get
around this we have to retry building and attaching (to refresh our view of
the kernel state), but this was never implemented.
Implement retry logic in program attach and detach; this relies on being
able to attach freplace programs to multiple dispatchers, so it'll fail on
kernels that are too old for that. But before we always failed if we hit
this race, so it's still an improvement.

libxdp: Add retries to handle some race conditions on attach and detach

---

headers/xdp/libxdp.h
lib/libxdp/README.org
lib/libxdp/libxdp.3
lib/libxdp/libxdp.c
lib/testing/test-tool.c
lib/util/params.c
lib/util/params.h
lib/util/util.c
lib/util/util.h
xdp-dump/xdpdump.c
xdp-filter/xdp-filter.c
xdp-loader/xdp-loader.c

This PR changes the libxdp handling of a missing bpffs to be more graceful.

libxdp: Better handling of missing bpffs

---

lib/libxdp/libxdp.c
xdp-dump/tests/test-xdpdump.sh

Extracted (and reworked) from #158

A couple of minor fixes to libxdp

---

lib/libxdp/libxdp_internal.h

The previous fix for the bounds check in libxdp_validate_opts() was incomplete (didn't fix the OPTS_ZEROED) macro. Change the code to use the same fix submitted to libbpf for its version of the same macros.

libxdp: Better fix for bounds check in libxdp_validate_opts()

---

.github/scripts/run_tests.sh
.github/scripts/run_tests_in_vm.sh
.github/workflows/selftests.yml
headers/linux/bpf.h
lib/libxdp/tests/test_runner.sh

Split out from #277 to investigate effect on CI selftests

Move libxdp selftests to their own name space

---

Makefile
configure
headers/xdp/libxdp.h
headers/xdp/xdp_stats_kern.h
headers/xdp/xdp_stats_kern_user.h
lib/libxdp/libxdp.c
lib/libxdp/libxdp.map
lib/testing/test_runner.sh
lib/util/params.c
lib/util/params.h
lib/util/stats.c
lib/util/stats.h
lib/util/util.c
lib/util/xdp_sample.c
xdp-bench/README.org
xdp-bench/xdp-bench.8
xdp-filter/xdp-filter.c
xdp-monitor/xdp-monitor.8
xdp-trafficgen/.gitignore
xdp-trafficgen/Makefile
xdp-trafficgen/README.org
xdp-trafficgen/tests/test-xdp-trafficgen.sh
xdp-trafficgen/xdp-trafficgen.8
xdp-trafficgen/xdp-trafficgen.c
xdp-trafficgen/xdp-trafficgen.h
xdp-trafficgen/xdp-trafficgen.kern.c
xdp-trafficgen/xdp_trafficgen.bpf.c

An XDP-based traffic generator utilising the "live packet mode" of BPF_PROG_RUN in the kernel.

Add XDP trafficgen

---

lib/libxdp/libxdp.c
xdp-trafficgen/xdp-trafficgen.c

Fix a couple of issues pointed out by coverity in the code that was recently
merged.

Some coverity fixes

---

lib/libxdp/libxdp.3
lib/testing/test_config.install.sh
lib/util/xdp_sample.c
packaging/rpm/xdp-tools.spec
version.mk
xdp-bench/Makefile
xdp-bench/xdp-bench.8
xdp-dump/xdpdump.8
xdp-filter/xdp-filter.8
xdp-loader/xdp-loader.8
xdp-monitor/Makefile
xdp-monitor/xdp-monitor.8
xdp-trafficgen/Makefile
xdp-trafficgen/tests/test-xdp-trafficgen.sh
xdp-trafficgen/xdp-trafficgen.8
xdp-trafficgen/xdp-trafficgen.c

Final packaging fixes + version bump for v1.3

xdp-tools v1.3

---

lib/util/util.c

In contrast to the lib/libxdp/libxdp.c variant, the function find_bpf_file() in the lib/util/util.c file does not check and use the environment variable LIBXDP_OBJECT_PATH to overwrite the default path, but always uses the default variable BPF_OBJECT_PATH, which is set at compile time. 
To unify the behavior, the behavior of the util.c variant is adapted to that of the libxdp.c variant.
Concerning issue #507 
Signed-off-by: Lukas Schreckenberg <lukas.schreckenberg@iosb-ina.fraunhofer.de>

xdpdump: Adapt the util.c find_bpf_file() to the libxdp.c variant
