xdp-project/xdp-tools

xdp-filter/xdp-filter.c, xdp-loader/xdp-loader.c
These array need to be NULL terminated or else segfaults will happen.
=> fix general use of struct enum_val arrays

xdp-dump/xdpdump.c, xdp-dump/xdpdump_bpf.c
When multiple interfaces are using the same pinned XDP program we
should only capture packets from the interface requested. Without this
fix packets from all interfaces using this XDP program are captured.
To replicate the issues load a XDP program (pinning it), and assign it
to multiple interfaces. For example:
$ bpftool prog load test_bpf.o /sys/fs/bpf/eelcos_prog
$ bpftool net attach xdpgeneric pinned /sys/fs/bpf/eelcos_prog dev eth0
$ bpftool net attach xdpgeneric pinned /sys/fs/bpf/eelcos_prog dev eth1
$ xdpdump -i eth1
The last command will also show packets from eth0.
=> xdp-dump: fix multiple interfaces using the same XDP program

headers/xdp/libxdp.h, lib/libxdp/libxdp.c, xdp-loader/xdp-loader.c
This adds API's to get the information needed to see what sub-programs are loaded for multi-programs.
The xdp-loader has been changed to show which programs are loaded on the interface.
These APIs are also needed for xdp-dump to figure out which programs to attach to.
=> APIs to get more program information, including xdp-loader using it

xdp-dump/README.org
Make is more clear what makes xdpdump different from other utilities that can tcpdump via a perf ring-buffer.
I don't know how to export the man page version.
=> xdp-dump: Explain why xdpdump is practial for debugging XDP

xdp-dump/README.org, xdp-dump/xdpdump.c
The Linux API does not provide the full name of the attached eBPF
entry function if it's longer than 15 characters. xdpdump will try to
guess the correct function name from the available BTF debug
information. However, if multiple functions exist with the same
leading name, it can not pick the correct one. It will dump the
available functions, and you can choose the correct one, and supply it
with the -m option. For example:
$ xdpdump -i eth0
ERROR: Can't identify the full XDP main function!
The following is a list of candidates:
xdp_test_prog_with_a_long_name
xdp_test_prog_with_a_long_name_too
xdp_test_prog_w
Please use the -m option to pick the correct one.
$ ./xdpdump -i eth0 -m xdp_test_prog_with_a_long_name
1588252724.025055871: @entry: packet size 102 bytes on if_index 2, rx queue 0 …
=> xdp-dump: add support for >16 XDP eBPF entry function names

configure, headers/xdp/libxdp.h, headers/xdp/prog_dispatcher.h, lib/common.mk, lib/defines.mk, lib/libxdp/libxdp.c, lib/libxdp/libxdp.map, lib/libxdp/xdp-dispatcher.c.in, lib/util/stats.c, lib/util/util.c, lib/util/util.h, xdp-dump/xdpdump.c, xdp-filter/xdp-filter.c, xdp-loader/xdp-loader.c
This is a rework of the libxdp API to avoid exposing the multiprog and
dispatcher internals, and instead have xdp_program-based attach and detach
functions, so we can have some freedom to change the internals without having to
touch the API.
This also reworks the lib/util functions to build on top of libxdp, and ports
all the command-line utilities to use it.
While I have runtime-tested xdp-loader, the other utilities are only compile
tested.
=> Rework libxdp API and use it in all utilities

xdp-dump/xdpdump.c
=> xdp-dump: on an exact match of bpf function do not accept partials

headers/linux/bpf.h
Also update headers/linux/bpf.h to get the new struct definitions.
=> libbpf: Update to latest upstream version

xdp-dump/xdpdump.c
When attaching to an interface when no program is loaded,
i.e. fallback/legacy mode, do not open the interface in 
promiscuous mode.
=> xdpdump: do not open interface in promiscuous mode

xdp-dump/README.org, xdp-dump/test-xdpdump.sh, xdp-dump/xdpdump.c
Add option to put interface in promiscuous mode.
=> xdp-dump: add promiscuous option

lib/util/util.c, lib/util/util.h
Sometimes an added address was not printed out by the status subcommand, even though it was filtered correctly.
=> lib/util: Fix skipping of keys while iterating map

xdp-filter/xdp-filter.c
If the filter was loaded with a feature set not containing ip, status
subcommand did not print out the filtered MAC addresses.
Signed-off-by: Štěpán Horáček <shoracek@redhat.com>
=> xdp-filter: Fix printing of filtered MAC addresses

lib/util/util.h, xdp-filter/xdp-filter.c
After commit aef3cac the last key was still skipped.
=> lib/util: Fix skipping of the last key in map

xdp-filter/test-xdp-filter.sh
Some times tcpdump gets terminated before it finishing reading the
buffers from the kernel. Rather than increasing the timeout, add the
"--immediate-mode" option to not delay any packet gathering.
In addition also removed the first 1 second delay, as it's already
part of the start_background shell function.
=> xdp-filters: fixed self test issue with tcpdump

lib/libxdp/Makefile
Makefile fails and prints
```
install: missing destination file operand after '/usr/local/share/man/man3'
Try 'install --help' for more information.
```
while installing without proper Emacs, since the MAN_FILES variable was empty.
=> libxdp: Fix installing without supported Emacs

xdp-loader/README.org, xdp-loader/xdp-loader.c
Previously we were loading programs without specifying an explicit mode by
default, letting the kernel pick. This causes problems for a couple of
reasons:
- It causes silent fallback from native to generic mode, making it harder
to predict which mode a program would be loaded in.
- There's an nfp driver bug which makes it harder to unload such programs.
Arguably, the default should have been to just load in native mode from the
start. So let's change the default, but let the user go back to the
kernel-picked mode by specifying '-m unspecified' when loading. Document
the change in defaults in the man page.
----
@shoracek discovered why the nfp driver was having issues with unloading programs.
Arguably we should have been using native …
=> xdp-loader: Change to loading programs in native mode by default

configure, lib/common.mk, lib/defines.mk, lib/libxdp/Makefile
Although we cross-compile, we use clang from the host. Setting
"-target=bpf" will result in the right format for the host system but
not for the actual target.
Clang has the feature that we can also cross compile directly for some
other architecture, i.e. we can use "bpfeb" and "bpfel".
If we want to use e.g. OpenWrt, then we would like to be able to compile
directly for the given architecture. OpenWrt has the nice feature
that we can check in the Makefile for "ifeq ($(CONFIG_BIG_ENDIAN),y)".
If we combine both, we can set the endianness automatically.
The default behavior remains by setting "-target=bpf".
=> configure: add BPF_TARGET for cross-compile

xdp-dump/xdpdump.c
=> xdpdump: Fix Coverity issue with append_snprintf()

configure, lib/libxdp/libxdp.c, lib/testing/test_runner.sh, lib/util/params.c, lib/util/util.c, lib/util/util.h, xdp-dump/xdpdump.c, xdp-loader/tests/test-xdp-loader.sh, xdp-loader/xdp-loader.c
The kernel now supports re-attaching an freplace program in multiple
places, which means we can finally implement incremental loading of
multiprogs. This involves no change in the API, it just means that
attaching a program to an interface that already has program(s) attached
now will work if the kernel is new enough (5.10+).
This also means we can support detaching a subset of the programs, by the same
mechanism of creating a new dispatcher and swapping it out atomically.
=> Support incremental attach and detach of subprograms

xdp-dump/tests/test-xdpdump.sh
=> xdpdump: skip mulitprog selftest if multiprog is not supported

headers/xdp/libxdp.h, lib/libxdp/libxdp.c, lib/libxdp/libxdp.map, xdp-loader/README.org, xdp-loader/xdp-loader.c
This PR implements a clean up function to check if a ifindex's dispatcher directory is stale, and removes the pinned directory. Optionally, passing ifindex 0 makes the helper walk the entire XDP bpffs directory, looking for stale entries.
This is now exposed to the user through the `xdp-loader collect [ifname]` command.
=> Add xdp_clean_references

.travis.yml, lib/libxdp/libxdp.c, lib/libxdp/xdp-dispatcher.c.in, lib/testing/test_runner.sh, xdp-dump/tests/test-xdpdump.sh, xdp-filter/xdp-filter.c, xdp-loader/tests/test-xdp-loader.sh
Older kernels do not support pinning of programs. Check if current kernel does and if it does not then use legacy program.
There is a problem with the fact that unlinking of the pin is non-blocking and therefore the test program might be still pinned while the real program is being linked. I tried to solve this by adding a timeout, but I am not sure if there is some more elegant solution.
I also set some tests to be skipped depending on the kernel version. This means two tests of xdp-loader for loading multiple programs and almost every test of xdpdump, since it cannot dump if there is legacy program already attached on the interface.
=> Check compatibility for pinning

headers/xdp/libxdp.h, lib/libxdp/libxdp.c, lib/libxdp/libxdp.map, xdp-dump/tests/test-xdpdump.sh, xdp-dump/xdpdump.c
One commit introduces this. Since the default behaviour is changed (causing e.g. xdpdump to not be able to be attached), the other commit disables it by default. This might fix issue #103, but while testing I did not see any noticeable difference in performance even between single legacy program and a program with non-freplaced dispatcher, but that might be just a bad testing setup.
=> Freplace dispatcher if there is only one program attached

xdp-dump/xdpdump_bpf.c
The code is awesome, but there is a typo in comment, so fix it. :)
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>
=> xdp-dump: fix typo in comment

xdp-dump/xdpdump.c
libbpf v1 no longer overloads pointers with an error value instead,
it uses errno. This fix will change the perf_buffer API to take this
into account.
=> xdpdump: Fix perf buffer API fixes to comply with new error checking.

xdp-dump/xdpdump_bpf.c, xdp-dump/xdpdump_xdp.c
=> xdpdump: Use new .maps section for map definitions to support BTF

xdp-dump/xdpdump.c
It is confusing that xdpdump buffers packets (via perf_attr.wakeup_events) when printing to stdout, as described in #130.
This fixes #130 by only buffering packet in the perf ring when cmdline option --write pcap_file have been specified.
Fixes: cbc47d53b275 ("xdp-dump: add support for multiple buffer wakeup")
=> xdpdump: only buffer in perf ring when using pcap_file

lib/libxdp/Makefile
These patches make it possible to build xdp-tools with clang.
=> Build with clang

.github/scripts/run_tests.sh, configure, headers/linux/bpf.h, headers/linux/btf.h, xdp-dump/tests/test-xdpdump.sh, xdp-filter/xdp-filter.c
It turns out that there actually *was* a real bug in xdp-filter which was the cause of the test breakage. However, because the bug was due to uninitialised memory being passed to the kernel, it only triggered occasionally and so it has apparently slipped by for quite some time.
While investigating the breakage, a couple of other errors surfaces, so fix all of them which should hopefully bring the tests back in good shape.
=> Unbreak selftests

.github/scripts/run_tests.sh, configure, headers/linux/bpf.h, headers/linux/btf.h, lib/libxdp/xsk.c, xdp-dump/tests/test-xdpdump.sh, xdp-filter/xdp-filter.c
If the legacy loading prodedures are used, xsk_lookup_program will
fail even if there is a program loaded on the interface because
xdp_multiprog__next_prog fails. To rectify this introduce a check for
legacy mode which if true, will skip the xdp_multiprog__next_prog call
and ensure the legacy program is returned.
Fixes: ea481a18ed07 ("libxdp: move AF_XDP functionality from libbpf")
Signed-off-by: Ciara Loftus <ciara.loftus@intel.com>
=> libxdp: fix program lookup for legacy

.github/workflows/covscan.yml, .github/workflows/release.yml, .github/workflows/selftests.yml
@rst0git pointed out that we can get the checkout action to also checkout
the submodule instead of relying on the configure script to do that for us.
Let's add that option to all workflows.
=> github/workflows: Add option to recursively checkout submodules

.github/scripts/prepare_test_tools.sh, lib/common.mk, lib/testing/.gitignore, lib/testing/Makefile, lib/testing/test-tool.c, xdp-dump/tests/test-xdpdump.sh
This commit adds a test-tool compiled binary to the testing
framework. The tool allows specific "C" tool needs to be
bundled in a single binary.
The first tool needed was a simple loader to get rid of the
bpftool used by the xdp-dump self-test.
Fixes #150
=> testing: add test-tool to testing framework with basic load

.github/scripts/prepare_test_tools.sh, .github/workflows/selftests.yml, headers/xdp/libxdp.h, lib/libxdp/libxdp.c, lib/libxdp/libxdp.map, lib/libxdp/libxdp_internal.h, lib/libxdp/protocol.org, lib/libxdp/xdp-dispatcher.c.in, lib/util/util.c, xdp-dump/xdpdump.c, xdp-dump/xdpdump_xdp.c, xdp-filter/xdp-filter.c, xdp-filter/xdpfilt_prog.h, xdp-loader/README.org, xdp-loader/tests/test-xdp-loader.sh, xdp-loader/xdp-loader.8, xdp-loader/xdp-loader.c
Since libbpf has deprecated custom section names and recommends usage of
bpf_object__find_program_by_name instead of bpf_program_by_section_name,
provide a new unified OPTS style xdp_program__create that can perform
XDP program creation using various options.
See commits for details.
Closes: https://github.com/xdp-project/xdp-tools/issues/153
Signed-off-by: Kumar Kartikeya Dwivedi <memxor@gmail.com>
=> libxdp: Introduce OPTS based xdp_program__create

lib/libxdp/libxdp.c, lib/testing/test_runner.sh
On architectures other than x86, falling back to regular loading of XDP
programs (without the dispatcher) is normal, so let's demote the log
messages about this so it doesn't show up by default when using xdp-loader.
=> libxdp: Demote log level for fallback messages

.github/workflows/selftests.yml
The selection of kernels we test with was getting old, let's add a 5.16
kernel to the mix.
=> github/workflows: Add a newer kernel to the test matrix

lib/Makefile
There's now a binary in testing/ which links against the objects in util/,
so we need to make sure util/ is built first or linking will fail.
Fixes: 669c7b433e70 ("testing: add test-tool to testing framework with basic load")
=> lib/Makefile: Make sure util is built before testing

.gitmodules, headers/xdp/libxdp.h
Add `extern C` to allow `libxdp` header to be included in C++ code.
Also, add `ignore=untracked` attribute to `.gitmodules`.
=> Add extern C to libxdp

lib/testing/test_runner.sh, xdp-dump/tests/test-xdpdump.sh, xdp-dump/xdpdump.c
=> xdp-dump: skip tests that need ftrace attach when not supported.

headers/xdp/xsk.h
Commit 8ed7e2696844 ("libxdp: export inline helpers as symbols in
libxdp") used C99 inline semantics to rely on inline without extern not
emitting a symbol, and extern inline declaration doing that instead. On
C89, these C99 inline semantics are not followed.
Instead of requiring users to migrate away from C89, we can still retain
compatibility by marking XDP_ALWAYS_INLINE as static inline, while
ensuring libxdp continues to expose these symbols.
Closes: #173
Fixes: 8ed7e2696844 ("libxdp: export inline helpers as symbols in libxdp")
Signed-off-by: Kumar Kartikeya Dwivedi <memxor@gmail.com>
=> xdp/xsk.h: Fix compilation with -std=gnu89

configure
The libelf library requires zlib. If zlib isn't installed the pkg-config check for libelf fails silently even if libelf is installed leading to a lot of confusion.
This patch moves the zlib check before libelf to catch this case.
Example of the error case where this was occurring for us:
```
% pkg-config --print-errors --exists libelf
Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zlib', required by 'libelf', not found
```
=> check for zlib before libelf in configure

configure
A couple of fixes to the configure script to aid debugging and embedding of xdp-tools as a git submodule.
=> A couple of configure fixes

packaging/rpm/xdp-tools.spec
The XSK BPF programs were put into the xdp-tools package instead of libxdp
by mistake. Fix this, and add the license files to the libxdp package as well.
=> RPM: XSK programs should be part of the libxdp package

headers/xdp/libxdp.h, lib/libxdp/libxdp.c, lib/libxdp/libxdp.map, lib/libxdp/libxdp_internal.h, lib/libxdp/xsk.c
Library users may need to clone xdp_program objects, so expose the internal
xdp_program__clone() method to do this. Add a flags argument for future
extensibility, and also handle unloaded xdp_program instances, by creating
a new program with an external reference to the same bpf_object.
Fixes #183.
=> libxdp: Expose xdp_program__clone()

lib/libxdp/libxdp.c
- This initialises a variable to 0, to allow libxdp to be built with -O3 optimisation.
- Without this initialisation, it fails due to 'version' potentially being used unitialised in the function.
=> - Initialising variable to allow build with -O3

lib/libxdp/xdp-dispatcher.c.in
Including <linux/in.h> is not actually necessary for the XDP
dispatcher, so drop the redundant include.
=> libxdp: Drop linux/in.h include for XDP dispatcher

lib/libxdp/libxdp.c
=> libxdp: cleanup references to undeclared variable using the proper variable name

lib/export-man.el, lib/libxdp/Makefile, lib/libxdp/libxdp.3, xdp-dump/xdpdump.8, xdp-filter/README.org, xdp-filter/xdp-filter.8, xdp-loader/README.org, xdp-loader/xdp-loader.8
The 'whatis' utility expects a man page to start with a NAME section with
the name and a short description of the utility. Add some regex hackery to
make sure our exported man pages conform to this format. For details, see:
https://www.mit.edu/afs.new/sipb/project/debathena/lintian/www/tags/manpage-has-bad-whatis-entry.html
Reported-by: Luca Boccassi <bluca@debian.org>
=> man pages: Reformat to support NAME heading for proper whatis processing

xdp-filter/xdp-filter.c
When updating the state map fails for xdp-filter, it doesn't actually print
any error messages, it just sets the return code as failed. Fix this,
special-casing the most common error (map full), and otherwise just
printing the error message returned by the kernel.
This should (partially) fix #201
=> xdp-filter: Print error message if updating state map fails

xdp-filter/xdp-filter.c
We never deleted elements from the hash maps used for IP address storage,
which meant that adding and removing IP addresses would cause the map to
keep growing, eventually overflowing. Fix this by deleting the element
entirely from the hash map when setting its flags to 0.
Should properly fix #201
=> xdp-filter: Delete elements from map when their flags are zero

configure
The Dash shell (which is used for /bin/sh on Debian and derivatives)
doesn't support the bracket-based header file expanding pattern we used to
copy over libbpf headers when LIBBPF_UNBUILT is set. Fix that by manually
expanding the brackets, and also complete the incomplete comment above the
code doing the copy.
=> configure: Expand bracket combination when copying libbpf headers

headers/linux/btf.h
Libbpf 1.0.0 fails to build with older versions of the btf.h header file
from the kernel because of a missing struct btf_enum64 definition. This was
not added in the upstream kernel until the 6.0 cycle, so this header update
is not yet in any released version of the kernel. Technically this makes it
a bit premature to import this, but seeing as libbpf already introduced a
dependency on the header file, let's do so anyway to work around the buggy
upstream.
Fixes #220
=> headers: Update kernel btf.h header file

lib/libxdp/xsk.c
Remove the unused variable outstanding_tx.
Signed-off-by: Magnus Karlsson <magnus.karlsson@intel.com>
=> xsk: remove unused variable outstanding_tx

lib/libxdp/README.org, lib/libxdp/libxdp.3
Now that we merged the XSK example programs into the bpf-examples
repository, we should update the links in the README to point to those
instead of the kernel samples directory.
Fixes #217.
=> libxdp: Update references to example programs in README

headers/xdp/parsing_helpers.h, xdp-filter/xdpfilt_prog.h
bpf_endian.h should always be put ahead of parsing_helpers.h,
otherwise loading prog will complain like below:
libbpf: failed to find BTF for extern 'bpf_htons': -2
So to make life easier, add it to the header file directly.
Signed-off-by: junka <wan.junjie@foxmail.com>
=> headers: add bpf_endian.h for parsing_helpers.h

xdp-filter/xdpfilt_prog.h
PR updates the comment on top of xdp-filter/xdpfilt_prog.h as there is no longer a `xdp_filt_kern.c` file.
=> xdp-filter: update comment in xdpfilt_prog.h

lib/export-man.el
The export-man Emacs function tries to read the file modification from the
git log, and falls back to the file modification if it can't. However, it
turns out that the shell-command-to-string Emacs function can actually
crash, so we need to wrap it in an 'ignore-errors' macro.
Fixes #240.
=> export-man: Ignore errors when executing git shell command

xdp-loader/README.org, xdp-loader/xdp-loader.8
We don't document that the 'hw' mode is unsupported on most hardware. Add a
note to the man page explaining this.
Fixes #170
=> xdp-loader/README: Mention lack of support for HW mode in most cards

lib/libxdp/libxdp.c
The check added to xdp_program__attach_single() in an earlier patch was
wrong: the bpf object survives after loading a program. Instead, check if
the fd has already been set and use that as an indicator for whether we
should load the program before attaching.
=> libxdp: Fix check in xdp_program__attach_single()

configure
The clang and llc binaries can be installed as versioned binaries named as
clang-$VERSION. In particular this happens when using the Debian and Ubuntu
packages from the apt.llvm.org repository. To make installation a bit
friendlier, teach the configure script to autodetect such binaries, by
trying each one in order from the newest (clang-16, llc-16) to the
oldest (clang-10, llc-10). We only do this if no explicit path is supplied
in the environment, and only if the non-versioned binary doesn't exist.
I.e., the objective here is to only do autodetection in cases where we
would otherwise fail configure because no binary was found.
=> configure: Try to auto-detect versioned clang binaries

.github/workflows/covscan.yml, lib/libxdp/libxdp_internal.h, lib/util/stats.c, lib/util/xdp_sample.c
Now that we require clang-11 to build, the covscan CI action fails. Update to the llvm-11 for this action as well.
=> .github/workflows: Update covscan tooling to clang-11

configure, xdp-bench/xdp_redirect_devmap.c, xdp-bench/xdp_redirect_devmap_multi.c
Add a configuration check to allow xdp-bench to build against old libbpf
versions, and fix a potential double-free error discovered in the process of
doing this.
=> Fix building xdp-bench against old libbpf versions

lib/libxdp/Makefile, lib/libxdp/libxdp.c, lib/libxdp/libxdp_internal.h, lib/libxdp/tests/Makefile, lib/libxdp/tests/test-libxdp.sh, lib/libxdp/tests/test_runner.sh, lib/libxdp/tests/test_utils.h, lib/libxdp/tests/test_xsk_refcnt.c, lib/libxdp/xsk.c, lib/libxdp/xsk_def_xdp_prog.c, lib/libxdp/xsk_def_xdp_prog_5.3.c
*Currently, if multiple userspace consumers reference the program,
when one of them decides to clean-up and detach the program,
others can not use it anymore. The most obvoius example of such
situation is AF_XDP. In libbpf it was resolved with the bpf_link
abstraction by commit 10397994d30f (libbpf: xsk: Use bpf_link),
but this is not an option in libxdp due to the heavy usage of pinning.*
*Therefore we need to have a separate refcount mechanism.*
This PR shows one way of doing this (details in the commit message).
I mainly expect a feedback on the concept itself.
I will probably refactor some stuff, if it isn't be rejected altogether.
I've tested the basic use cases, so it does certainly work.
If the concept is approved, the following commits will follow:
- refcount API for the …
=> libxdp: Introduce refcount

xdp-bench/Makefile, xdp-bench/README.org, xdp-bench/tests/test-xdp-bench.sh, xdp-bench/xdp-bench.8, xdp-bench/xdp-bench.c, xdp-bench/xdp-bench.h, xdp-bench/xdp_basic.bpf.c, xdp-bench/xdp_basic.c, xdp-bench/xdp_redirect_basic.c
It seemed odd to not support XDP_PASS in xdp-bench, so add a 'pass' action
as well, reusing the same code as 'drop' and 'tx', which is already
identical apart from the return code. Rename 'droptx' to 'basic' everywhere
in the code to support this.
=> xdp-bench: Add pass action

xdp-loader/README.org, xdp-loader/xdp-loader.c
Support passing run priority and chain call actions at runtime, instead of using the static prio/actions in the ELF file. With these options, we can change the prio/actions as we want and no need to change the code and recompile them to ELF file.
Signed-off-by: Dongdong Wang <wangdongdong.6@bytedance.com>
=> xdp-loader: Support setting pri/act at runtime.

lib/libxdp/xsk.c
The marco `XDP_FLAGS_SUPPORTED` is only used in `xsk_convert_xdp_flags` and only contains flags about XDP mode.  
This would lead to warning output when invoker passes other flag like `XDP_FLAGS_UPDATE_IF_NOEXIST`.  
Let's replace it with `XDP_FLAGS_MASK` to supress such unnecessary warning. :)
=> libxdp: Supress unnecessary warning when converting xdp flags.

headers/xdp/xsk.h
Sparse checker doesn't have __GNUC_GNU_INLINE__ or __GNUC_STDC_INLINE__ defined, the same will be true for any non-GNU compiler.
This is causing build failures due to XDP_ALWAYS_INLINE being undefined.
This is potentially not the best way of fixing the problem, but it solves the current issue.
Closes: #279
Fixes: 83549d3a2e66 ("xdp/xsk.h: Fix compilation with -std=gnu89")
Reported-by: David Marchand \<dmarchan@redhat.com\>
Signed-off-by: Ilya Maximets \<i.maximets@ovn.org\>
=> xdp/xsk.h: Fix undefined XDP_ALWAYS_INLINE with sparse

.github/workflows/selftests.yml, lib/testing/test_runner.sh
Add a 6.1 kernel to the test matrix. Also remove a leftover command from the
test runners.
=> Update CI to a newer kernel

lib/libxdp/libxdp.c, xdp-loader/tests/test-xdp-loader.sh
Turns out libxdp would cheerfully clobber legacy progs when loading. Fix this to
disallow loading in the presence of an existing legacy program (forcing users to
manually unload first).
=> libxdp: Don't clobber legacy progs

headers/xdp/libxdp.h, headers/xdp/prog_dispatcher.h, lib/libxdp/libxdp.c, lib/libxdp/libxdp.map, lib/libxdp/libxdp_internal.h, lib/libxdp/protocol.org, lib/libxdp/tests/.gitignore, lib/libxdp/tests/Makefile, lib/libxdp/tests/check_kern_compat.c, lib/libxdp/tests/test-libxdp.sh, lib/libxdp/tests/test_dispatcher_versions.c, lib/libxdp/tests/test_runner.sh, lib/libxdp/tests/test_utils.h, lib/libxdp/tests/test_xdp_frags.c, lib/libxdp/tests/xdp_dispatcher_v1.c, lib/libxdp/tests/xdp_dispatcher_v1.h, lib/libxdp/tests/xdp_pass.c
To enable the use of XDP with large MTUs, the kernel added support for
addressing multiple packet fragments from XDP, AKA "XDP frags" in kernel
version 5.18. This support is opt-in from the program side since it changes
the semantics of the XDP program: The full packet data is no longer
guaranteed to be addressable through the data and data_end pointers of the
XDP context object, and the XDP program has to use a new API to access
packet data after the first fragment.
An XDP program opts in to using this support by setting the
BPF_F_XDP_HAS_FRAGS flag when loading a program, and the kernel only allows
attaching an XDP program to a large-MTU device if this flag is set.
However, because libxdp did not understand the flag, frags support could
not be used at all with libxdp (even if a program …
=> libxdp: Add support for loading programs with frags support

lib/libxdp/tests/test-libxdp.sh, lib/libxdp/tests/test_runner.sh
The libxdp selftests were leaking the temporary directory it was creating.
Move the creation and deletion into the tests that actually use it instead
of having a global one created in test-runner.sh.
=> libxdp: Make sure we cleanup the temporary directory in selftests

lib/libxdp/libxdp.c
A recently added 'switch' statement for handling different dispatcher types includes a line of code where a variable is declared immediately after a case label without being enclosed in braces.
This causes compilation failures with certain compilers, which appear as:
libxdp.c: In function 'check_dispatcher_version':
libxdp.c:2189:3: error: a label can only be part of a statement and a declaration is not a statement
2189 |   struct xdp_dispatcher_config_v1 *config = (void *)buf;
|   ^~~~~~
Adding braces around the code for the case will avoid this problem.
Observed when following the standard build instructions on Ubuntu 20.04 (gcc 9.4.0, clang 15.0.7).
=> Fix compile error due to variable declaration inside a 'switch' case

lib/common.mk, xdp-bench/Makefile, xdp-monitor/Makefile
xdp_sample uses floor()/ceil() so every executable that imports that module needs to link with -lm. E.g. on armhf:
```
gcc -Wall -O2 -g -std=gnu11 -Wextra -Werror -DBPF_DIR_MNT=\"/sys/fs/bpf\" -DBPF_OBJECT_PATH=\"/usr/local/lib/bpf\" -DMAX_DISPATCHER_ACTIONS=10 -DTOOLS_VERSION=\""1.3.0"\" -DLIBBPF_VERSION=\"1.1.0\" -DRUNDIR=\"/run\" -DHAVE_LIBBPF_PERF_BUFFER__CONSUME -DHAVE_LIBBPF_BTF__LOAD_FROM_KERNEL_BY_ID -DHAVE_LIBBPF_BTF__TYPE_CNT -DHAVE_LIBBPF_BPF_OBJECT__NEXT_MAP -DHAVE_LIBBPF_BPF_OBJECT__NEXT_PROGRAM -DHAVE_LIBBPF_BPF_PROGRAM__INSN_CNT -DHAVE_LIBBPF_BPF_MAP_CREATE -DHAVE_LIBBPF_PERF_BUFFER__NEW_RAW -DHAVE_LIBBPF_BPF_XDP_ATTACH -DHAVE_LIBBPF_BPF_MAP__SET_AUTOCREATE -DHAVE_LIBBPF_BPF_PROG_TEST_RUN_OPTS -DHAVE_SECURE_GETENV -DLIBBPF_DYNAMIC -D_LARGEFILE64_SOURCE …
```
=> Link with -lm to fix build on arm/mips/risc/ppc

lib/libxdp/libxdp.c
At higher optimisation levels, the compiler seems to think that the NULL
check in xdp_program__name() implies that the prog pointer can be NULL.
Which makes it complain about the unconditional use in debug output with
somewhat cryptic errors like:
In file included from libxdp.c:37:
libxdp.c: In function ‘xdp_multiprog__pin’:
libxdp_internal.h:38:37: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
38 |                 libxdp_print(level, "libxdp: " fmt, ##__VA_ARGS__); \
|                                     ^~~~~~~~~~
libxdp_internal.h:43:28: note: in expansion of macro ‘__pr’
43 | #define pr_debug(fmt, ...) __pr(LIBXDP_DEBUG, fmt, ##__VA_ARGS__)
|                            ^~~~
libxdp.c:3097:17: note: in expansion of macro ‘pr_debug’
3097 | …
=> libxdp: Use prog->prog_name directly in debug output

xdp-loader/xdp-loader.c
When xdp-loader is loading a BPF object file it'll do so through the libbpf
bpf_object__load() API. This loads the whole BPF object, including all BPF
programs defined in the object file. Apart from being wasteful (those
programs will just get unloaded from the kernel when xdp-loader exits),
this can also make loading fail if one of those programs are unable to be
loaded for whatever reason.
The concrete failure that was observed for this is older object files that
don't use the new-style SEC("xdp"), in which case libbpf will fail to set a
program type. For the program we're targeting as loading, libxdp will reset
the program type (to attach to a dispatcher), so we can load such programs,
but extra programs in the same object file that are compiled like this will
fail for no good reason. …
=> xdp-loader: Only load the BPF program we need from object files

configure
The configure check for btf__type_cnt() swapped two arguments in the
check_libbpf_function() call in the configure script, leading to the check
failing if LIBBPF_CFLAGS is non-empty. Make sure the arguments are in the
right order, and also pass a proper NULL parameter in the check instead of
a 0.
Fixes #298.
=> configure: Fix function detection for btf__type_cnt()

lib/defines.mk
The clang toolchain might have stack-protection enabled by default (e.g. via platform configuration) and that won't work for BPF, so unconditionally disable it via -fno-stack-protector.
Fixes #299
=> make: disable stack protector for BPF bits built by clang

xdp-dump/Makefile
When building all of xdp-tools with clang, the xdp-dump build fails due to 'classic' use of variable-length arrays and -Werror. Disable the warning and leave a breadcrumb to the discussion.
Fixes: #304
=> xdpdump: fix build with clang

lib/libxdp/libxdp.c
In musl, PATH_MAX is defined in limits.h. Include it in libxdp.c to fix building systems using musl libc.
libxdp.c: In function 'find_bpffs':
libxdp.c:406:33: error: 'PATH_MAX' undeclared (first use in this function)
406 |         static char bpf_wrk_dir[PATH_MAX];
|                                 ^~~~~~~~
=> libxdp: fix build on musl

lib/libxdp/tests/test_xdp_frags.c
As currently written, `test_xdp_frags` if run without necessary permissions will loudly print "this kernel does NOT support xdp frags", and then exit on the `setrlimit()`. The same thing happens if the argument list is invalid. Instead, verify all this before performing the frag support check, so as not to dismay users (like me) who try using this program to check for frag support.
I didn't touch the formatting in this file so as to produce a minimal diff for review, but it's kinda all over the place.
=> test_xdp_frags: check for privs early

lib/util/xdp_sample.bpf.c
The bpf_trace_vprintk() helper was added to the libbpf headers in 0.6.0, so define it if it doesn't exist. We already detect the bpf_program__flags() helper which was added in the same version, so just use that define to guard the definition.
=> util/xdp_sample: define bpf_trace_vprintk() if it doesn't exist

xdp-loader/xdp-loader.c
In xdp-loader we explicitly silence libbpf logging before loading a program
because the output is unhelpful in most cases. With the addition of
multiprog probing we also get unhelpful output on unload, so also silence
the output there.
Reported-by: Simon Sundberg <Simon.Sundberg@kau.se>
=> xdp-loader: also silence libbpf logging on unload

lib/util/params.c, lib/util/util.c, lib/util/util.h, xdp-filter/xdp-filter.c
The dispatch_commands() helper takes a program lock and holds it while the
command is being executed. This was added for the use of xdp_filter, and is
really only needed for that; none of the other utilities really need
locking to synchronise with itself (and libxdp has its own locking for the
dispatcher).
Move the locking out of dispatch_commands() and instead add explicit lock
and unlock calls to each of the xdp-filter commands. While doing so, also
move the locking to use the same directory-fd based approach as the libxdp
locking uses. This has the benefit of not writing any lock files, so the
lock is automatically cleared when the application exits, even if it
crashes. This should fix any issues with stale lock files sticking around,
which we did not have any good way to clean up. …
=> util: Move program locking out of dispatch_commands()

configure, lib/testing/test-tool.c, lib/util/compat.h, lib/util/xdp_sample.h, xdp-trafficgen/xdp_trafficgen.bpf.c
The xdp_samples.h file was using some newer libbpf functions without the
required compatibility defines, leading to compilation errors on older
libbpf versions. Add the required defines to util/compat.h and include that
from xdp_sample.h. This includes a new configure check for
bpf_program__expected_attach_type(), which was renamed in libbpf 1.0.
Fixes #326
=> util/xdp_samples: Add compatibility defines for libbpf

configure, headers/linux/netdev.h, xdp-loader/README.org, xdp-loader/tests/test-xdp-loader.sh, xdp-loader/xdp-loader.8, xdp-loader/xdp-loader.c
Add features command to xdp-loader in order to dump XDP features supported by the NIC
=> xdp loader features

lib/common.mk, lib/libxdp/Makefile, lib/util/xdp_sample.h
Some minor packaging-related changes while trying to package v1.3.1:
- Install BPF/XDP objects as non-executable to keep their symbol table from being stripped (only tested on openSUSE's build system though)
- Support GCC 7 and earlier
- Add a minimum version requirement for libbpf
=> Minor packaging improvements

headers/xdp/xsk.h, lib/libxdp/README.org, lib/libxdp/libxdp.3, lib/libxdp/libxdp.map, lib/libxdp/xsk.c
Adding a new API xsk_umem__create_with_fd() that accepts an extra file descriptor of already open AF_XDP socket.  This function can be used as a substitute of a regular xsk_umem__create() in case where process doesn't have CAP_NET_RAW privileges.  Privileged process may open a socket beforehand and send the file descriptor via UNIX domain socket or pass it during exec().  Subsequent xsk_socket__create() will re-use this socket.  No other operations require privileges in case the program load is inhibited.
This change allows use of AF_XDP with libxdp by processes with no extra privileges.
xsk_socket__create_shared() requires opening a new socket for each queue after the first one, so it will require more work in order to create a pretty API.  Not doing that right now.  The target use-case …
=> libxdp: Allow creation of xsk with exclusive umem without CAP_NET_RAW

.github/workflows/selftests.yml, configure, lib/libxdp/tests/.gitignore, lib/libxdp/tests/Makefile, lib/libxdp/tests/test-libxdp.sh, lib/libxdp/tests/test_xsk_non_privileged.c
Test loads a program, creates bare AF_XDP socket, then drops all the capabilities and tries to create umem and xsk with previously created resources.
Uses libcap-ng as a dependency for capability management.  Skipped if the library is not available at the configuration time.
=> libxdp: Add selftest for non-privileged xsk creation

lib/libxdp/Makefile
Gentoo CI previously reported symbol mismatches in libxdp (see #302 and https://bugs.gentoo.org/899742) when multiple toolchains are installed. This was caused by a direct call to 'readelf' instead of using the command injected by the environment/toolchain.
The fix is simple: use $(READELF).
=> libxdp: don't use direct call to readelf for symbol table comparison

.github/workflows/selftests.yml
New versions of bpftool fail to compile on clang-11, so let's just bump the
version used in the CI to clang-16.
=> .github/workflows: Bump Clang version to clang-16

lib/libxdp/libxdp.c
All fd that are taken from bpf shall be closed right after they were cloned:
`fd = bpf_prog_get_fd_by_id(id);`
=> Fix bpf program original file  descriptor management

lib/util/xdp_sample.c
Having buffering enabled (by default in linux) for `stdout` causes issues for pipes. Since pipe buffer is pretty large (64KiB) it would take ages to fill that up. Therefore, applications in pipe are "unable" to reliably read `xdp-bench`'s `stdout`.
This approach may affect performance, but since `xdp-bench` tool does not rely on `stdout`/`stderr` operations, it's safe to flush both `stdout` and `stderr` buffers immediately.
before:
```python
>>> import time
>>> import subprocess as s
>>> p = s.Popen("xdp-bench drop eno12399", stdout=s.PIPE, stderr=s.PIPE, shell=True)  # piped back to python process
>>> time.sleep(15)
>>> p.kill()
>>> p.communicate()
(b'', b'Dropping packets on eno12399 (ifindex 4; driver ice)\n')  # (stdout, stderr)
>>>
```
after:  
```python
>>> import subprocess as s …
```
=> xdp-bench: flushing outputs after writing stats

lib/libxdp/libxdp.c, lib/libxdp/tests/.gitignore, lib/libxdp/tests/Makefile, lib/libxdp/tests/test-libxdp.sh, lib/libxdp/tests/test_link_detach.c
supporting force detach for link based attachments using `xdp-loader unload -a <intf>` fixes #361
=> Support detaching xdp_link-based attachments fix #361

xdp-trafficgen/xdp-trafficgen.c
The must C library doesn't have the fancy union define that glibc has for
the various sockaddr structs, so it barfs on the use of a sockaddr_in6 as
an argument to getsockname(). Add an explicit cast to avoid the error.
Fixes #346
=> xdp-trafficgen: Cast argument to getsockname() to struct sockaddr

lib/libxdp/libxdp.c, lib/libxdp/tests/test_link_detach.c
we need to be able to handle skb and native modes to avoid this
```sh
Unable to detach XDP program: Device or resource busy
CURRENT XDP PROGRAM STATUS:
Interface        Prio  Program name      Mode     ID   Tag               Chain actions
--------------------------------------------------------------------------------------
lo                     <No XDP program loaded!>
eno1                   <No XDP program loaded!>
eno2                   <No XDP program loaded!>
ens5f0                 <No XDP program loaded!>
ens5f1                 <No XDP program loaded!>
gre0                   <No XDP program loaded!>
gretap0                <No XDP program loaded!>
erspan0                <No XDP program loaded!>
ovs-system             <No XDP program loaded!>
genev_sys_6081         <No XDP program …
```
=> need to support xdp detach link for skb and native modes

lib/libxdp/Makefile
libxdp: Move hard-coded -DLIBXDP_STATIC=1 compiler flag into a new variable called STATIC_CFLAGS inline with the SHARED_CFLAGS variable to improve Makefile consistency.
=> libxdp: Move hard-coded -DLIBXDP_STATIC=1 compiler flag into a new

xdp-bench/README.org, xdp-bench/xdp-bench.c, xdp-bench/xdp-bench.h, xdp-bench/xdp_redirect_cpumap.bpf.c, xdp-bench/xdp_redirect_cpumap.c
These modes assigns CPUs based on L4 source and dest port. This is useful for load testing scenarios where you can assign sequential source ports to flows (like with neper).
For router/gateway use cases you use sport mapping on the forward direction and dport mapping on the reverse direction.
=> xdp-bench: Add l4-sport and l4-dport cpumap modes

lib/libxdp/xsk.c
In the xsk_setup_xdp_prog function, the xsk structure temporarily takes ownership of an xdp_prog and stores it in ctx->xdp_prog. However, the allocated xdp_prog is not freed in xsk_destroy_xsk_struct, leading to a memory leak. This commit addresses the issue by adding a call to xdp_program__close to properly release the allocated xdp_prog memory.
=> libxdp: Fix xdp prog memory leak in xsk_setup_xdp_prog

configure
Hello!
I hope you're doing well.
Thank you very much for working on this code.
I recently did build with clang-17 from https://apt.llvm.org/ and it uses name of binary with suffix "-17": clang-17 which is not supported by configure script.
I added 17 as possible suffix for clang compiler name.
=> Added support for clang-17 in configure script

xdp-bench/xdp_basic.c
Before this commit, the XDP_TX message was used for the XDP_PASS case.
=> xdp-bench: Add correct logging message for XDP_PASS

xdp-bench/README.org, xdp-bench/xdp-bench.8
Update the readme and manpage to match the values in xdp-bench.c.
=> xdp-bench: Fix packet-operation values in documentation

xdp-bench/tests/test-xdp-bench.sh, xdp-bench/xdp_basic.bpf.c, xdp-bench/xdp_basic.c
In some network driver implementations, the linear part of the xdp_buff structure might be empty, with all data stored in the frags section. Accessing packet data directly is impossible in this case, and requires an API like the bpf_xdp_load/store_bytes helpers or dynptr.
This pull request ensures support for all xdp-bench packet operations (swap-macs, read-data, etc.) of basic actions (DROP, PASS, TX) when the linear part is empty.
The next step is to extend this functionality to the REDIRECT actions and explore integration with other tools beyond xdp-bench. After that, the plan is to introduce the option to use the superior dynptr API as another packet access alternative.
=> xdp-bench: Add support for xdp_buff with empty linear part

xdp-dump/tests/test-xdpdump.sh
kernel updated the promiscuous mode message in below commit, so update the previous check condition.
net/core: refactor promiscuous mode message
old message:
[  406.034418] device eth0 entered promiscuous mode 
[  408.424703] device eth0 left promiscuous mode
new message:
[  406.034431] ice 0000:17:00.0 eth0: entered promiscuous mode 
[  408.424715] ice 0000:17:00.0 eth0: left promiscuous mode
=> xdp-dump: add check for new promiscuous mode message in tests

xdp-forward/xdp-forward.c
**OS: ubuntu2204.localdomain 5.15.0-91-generic
compile error:**
xdp-forward.c: In function ‘do_load’:
xdp-forward.c:139:24: error: implicit declaration of function ‘bpf_object__next_program’; did you mean ‘bpf_object__unpin_programs’? [-Werror=implicit-function-declaration]
139 | while ((prog = bpf_object__next_program(skel->obj, prog)) != NULL)
| ^~~~~~~~~~~~~~~~~~~~~~~~
| bpf_object__unpin_programs
xdp-forward.c:139:22: error: assignment to ‘struct bpf_program *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
139 | while ((prog = bpf_object__next_program(skel->obj, prog)) != NULL)
| ^
xdp-forward.c:140:21: error: implicit declaration of function ‘bpf_program__type’; did you mean ‘bpf_program__size’? [-Werror=implicit-function-declaration]
140 | if …
=> fix compile xdp-forward fail

xdp-loader/README.org, xdp-loader/xdp-loader.8
There appears to have been a mixup in the [original PR] in the list of card with HW support.
Solarflare cards do not have HW support, only Netronome/Corigine cards do.
[original PR]: https://github.com/xdp-project/xdp-tools/pull/243
=> xdp-loader/README: netronome cards have HW support

xdp-forward/tests/test-xdp-forward.sh
Test IPv6 in test_fwd_full and test_fwd_direct and not IPv4 twice.
=> xdp-forward: fix typos in test-xdp-forward.sh

lib/common.mk
The current build system sets the name of the generated skeleton directly to the file's name minus the `.skel.h` suffix.
Passing names of eBPF targets that contain a directory will result in wrong names e.g. `bpf/xdp_program.bpf.o` will have a skeleton file of the name `bpf/xdp_program.skel.h` and consequently the program name will be `bpf/xdp_program` instead of `xdp_program`. The commit pops out the directory part from the name.
=> Set BPF Skeleton name to base name of ebpf file

.github/workflows/selftests.yml, headers/linux/hlist.h, headers/linux/netfilter.h, lib/testing/test_runner.sh, xdp-forward/Makefile, xdp-forward/README.org, xdp-forward/tests/test-xdp-forward.sh, xdp-forward/xdp-forward.8, xdp-forward/xdp-forward.c, xdp-forward/xdp_flowtable.bpf.c, xdp-forward/xdp_flowtable_sample.bpf.c
Introduce xdp-fwd-flowtable sample in order to perform XDP_REDIRECT between net_devices inserted in a netfilter flowtable.
=> xdp-forward: Introduce xdp-fwd-flowtable support

lib/testing/test_runner.sh, xdp-filter/tests/test-xdp-filter.sh, xdp-forward/tests/test-xdp-forward.sh, xdp-trafficgen/tests/test-xdp-trafficgen.sh
Use socat as default utility for tcp/udp client/server connections
=> Use socat as default utility for tcp/udp client/server connections

lib/util/xdp_sample.c
In the musl libc environment, `<sys/sysinfo.h>` also defines the `sysinfo` struct, causing a redefinition conflict:
```cpp
toolchain-x86_64_gcc-14.2.0_musl/include/linux/kernel.h:5,
from ../../headers/linux/hashtable.h:15,
from xdp_sample.c:33:
toolchain-x86_64_gcc-14.2.0_musl/include/linux/sysinfo.h:8:8: error: redefinition of 'struct sysinfo'
8 | struct sysinfo {
|        ^~~~~~~
In file included from xdp_sample.c:24:
toolchain-x86_64_gcc-14.2.0_musl/include/sys/sysinfo.h:10:8: note: originally defined here
10 | struct sysinfo {
|        ^~~~~~~
```
<br>
This commit removes the `<sys/sysinfo.h>` include.
It seems that none of its symbols are used in the `xdp_sample` code anyway.
=> util/xdp_sample: remove <sys/sysinfo.h> for musl compatibility

headers/linux/if_xdp.h, headers/xdp/xsk.h, lib/libxdp/libxdp.map, lib/libxdp/xsk.c
Currently, we cannot assign metadata length in param `config` when calling `xsk_umem__create()`. This PR adds the support to assign `tx_metadata_len` when creating umem.
Also, adding `xsk_umem__create_opts()` to provide a new way to create umem by opts macro.
=> libxdp: Add tx_metadata_len/xsk_umem__create_opts() to support AF_XDP Tx metadata

xdp-bench/xdp_redirect_basic.c, xdp-bench/xdp_redirect_devmap.c
Before this commit, the redirect dummy programs would fail to load on interfaces with non-linear MTU.
=> xdp-bench: Enable the xdp_frags flag for dummy programs

xdp-bench/README.org, xdp-bench/tests/test-xdp-bench.sh, xdp-bench/xdp-bench.8, xdp-bench/xdp-bench.c, xdp-bench/xdp-bench.h, xdp-bench/xdp_redirect_basic.bpf.c, xdp-bench/xdp_redirect_basic.c
This pull request extends the --load-mode flag functionality to xdp_redirect_basic.
This continues the work done in pull request #409,
to ensure support for the xdp-bench basic redirect action when the linear part is empty.
=> xdp-bench: Add support for the redirect action with --load-mode load-bytes

lib/libxdp/README.org, lib/libxdp/libxdp.3, lib/libxdp/xsk.c
Edit documentation for creating XSk umem by opts, with minor format fix.
This is a follow-up to the previous work [PR#443](https://github.com/xdp-project/xdp-tools/pull/443)
=> libxdp: Doc adaptation for XSk umem opts-creation

configure, lib/libxdp/Makefile, lib/libxdp/libxdp.map, lib/libxdp/libxdp.mk
- **configure: improve portability**
- **libxdp: improve portability**
- **configure: detect systems without gcc**
- **libxdp: improve portability**
No functional changes intended
=> improve portability

headers/xdp/xsk.h, lib/libxdp/libxdp.map, lib/libxdp/xsk.c
Introduce a new API xsk_socket__create_opts() to create XDP socket using opts struct. Note that if one of fill and comp is unset, the semantic of the new API is the same as xsk_socket__create(), otherwise the same as xsk_socket__create_shared().
=> libxdp: Use opts to create XDP socket

headers/xdp/xsk.h, lib/libxdp/tests/test_xsk_non_privileged.c, lib/libxdp/tests/test_xsk_refcnt.c, lib/libxdp/xsk.c
Use `umem`'s `fill_save` and `fill_comp` if `fill` and `comp` in opts are both unset when calling `xsk_socket__create_opts()`, otherwise use what they are set in opts. Add validation for only one of `fill` and `comp` are set.
This is to keep the same semantic as `xsk_socket__create()` and `xsk_socket__create_shared()`.
Also, use opts-style API to create XDP socket in libxdp tests.
=> libxdp: Modify semantic of fill and comp in xsk_socket_opts, with tests edited

lib/libxdp/tests/test_xsk_non_privileged.c, lib/libxdp/tests/test_xsk_refcnt.c
Use opts-style API to create umem in libxdp tests.
This is a follow-up to the previous work https://github.com/xdp-project/xdp-tools/pull/443
=> libxdp: Use opts-style API to create umem in libxdp tests

xdp-trafficgen/xdp-trafficgen.c
Fixes: 063ec71bea69 ("xdp-trafficgen: Support specifying the packet size for UDP packets")
=> xdp-trafficgen: fix typo in log message detected by Lintian

lib/libxdp/tests/.gitignore, lib/libxdp/tests/Makefile, lib/libxdp/tests/test-libxdp.sh, lib/libxdp/tests/test_xsk_umem_flags.c, lib/libxdp/xsk.c
The commit in the fixes tag made an uneccesary and incorrect attempt at backwards compatibility with kernels that do not support tx_metadata_len.
The kernel will either expect a size matching its version of struct xdp_umem_reg, if it encounters a shorter size, clamp it to 24 byte struct xdp_umem_reg_v1 [0].
The code in question attempted to provide a 28 byte length when tx_metadata_len was not set, which would invoke the kernel v1 processing.
This causes issues downstream as revealed in the Open vSwitch system testsuite.
I have confirmed that by removing this conditional, the test passes both on 6.7 and newer kernels.
0: https://github.com/torvalds/linux/blob/0ad2507d5d93/net/xdp/xsk.c#L1369-L1372
Fixes: 44b5e00692db ("libxdp: Add tx_metadata_len/xsk_umem__create_opts() to support AF_XDP …
=> libxdp: Fix incorrect setsockopt xdp_umem_reg size.

configure, lib/Makefile
When xdp-tools builds the embedded copy of libbpf, it invokes the libbpf build system to installs it headers, and then constructs a path to those embedded libbpf headers based on the assumption that libbpf installed its headers into its default PREFIX (which appears to be /usr):
https://github.com/xdp-project/xdp-tools/blob/7b3bbe2f6f16d658bb09a7b7e5958f4a49825ee6/configure#L382
However, if PREFIX is passed to the xdp-tools build system, this variable gets passed down to the invocation of the libbpf build system as well, and libbpf installs its headers into a different directory that doesn't match xdp-tools' LIBBPF_INCLUDE_DIR variable, and the build fails like this:
$ make PREFIX=/usr/local
[…]
libbpf support: Submodule 'libbpf' (https://github.com/libbpf/libbpf.git) registered for path …
=> Explicitly set PREFIX=/ when installing embedded libbpf headers

lib/util/xdp_sample.c
Also store the PPS values into the output container in
stats_get_devmap_xmit_multi(), since the PPS values are what we are
printing in the summary lines now.
Fixes: 7b3bbe2f6f16 ("util/xdp_sample: Print PPS values in summary line instead of totals")
Fixes #482
=> util/xdp_sample: Collect PPS values for stats_get_devmap_xmit_multi()

xdp-dump/xdpdump.h
Increase MAX_CPUS from 256 to 512 to support higher cpu count systems.
Fixes #485
=> Increase MAX_CPUS to 512

lib/defines.mk
The configure script may add extra include directories to CFLAGS, but
these were not propagated to BPF_CFLAGS, which leads to build errors
when libbpf is in an unusual place. Add an explicit propagation of
any CFLAGS starting with -I to BPF_CFLAGS.
Fixes #496
=> lib/defines: Propagate include directories to BPF_CFLAGS

lib/util/util.c, lib/util/util.h, xdp-loader/xdp-loader.c, xdp-trafficgen/tests/test-xdp-trafficgen.sh, xdp-trafficgen/xdp-trafficgen.c, xdp-trafficgen/xdp_trafficgen.bpf.c
Add logic to xdp-trafficgen to load a dummy program to an interface if needed,
and to abort running if the interface doesn't support the `ndo_xdp_xmit()`
operation.
Fixes #354
=> xdp-traffigen: Better handling of missing interface support

.github/workflows/selftests.yml, lib/libxdp/xdp-dispatcher.c.in, lib/testing/Makefile, lib/testing/xdp_adjust_tail.c, xdp-loader/tests/test-xdp-loader.sh
Newer kernels added checks that disallow replacing functions that don't modify
the packet pointer with ones that do. For libxdp this means that programs that
modify the packet pointer refuses to load. Fix this by adding the recommended
workaround to the dispatcher program.
Fixes #503
=> Add compatibility workaround for programs that invalidate the packet pointer

xdp-trafficgen/xdp-trafficgen.c
Probe does not work w/o "-i" option.
Fix the error by adding END_OPTIONS to probe_options.
$ sudo xdp-trafficgen probe -i ens5
Missing required option '--interface'
Usage: xdp-trafficgen [options] <hostname>
Use --help (or -h) to see full option list.
=> xdp-trafficgen: fix probe_options missing END_OPTIONS

.github/scripts/prepare_test_tools.sh, .github/scripts/run_tests_in_vm.sh, .github/workflows/selftests.yml, lib/libxdp/Makefile, lib/libxdp/libxdp.c, lib/libxdp/tests/test_runner.sh, lib/testing/test_runner.sh, xdp-dump/tests/test-xdpdump.sh, xdp-dump/xdpdump.c, xdp-filter/tests/test-xdp-filter.sh, xdp-forward/tests/test-xdp-forward.sh
This series makes a bunch of improvements to the test runners to make the tests
run faster. This consists of removing a bunch of sleep-based waits in favour of
explicit waits on particular output for the background processes.
Together, these changes reduce the time of a full 'make test' run from about
nine minutes, to just under one minute on my machine.
=> Improve selftest execution time
